//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDR_MAINMENU                    101
#define ID_FILE_EXIT                    102
#define ID_TASK_NEW                     103
#define ID_TASK_DELETE                  104
#define ID_TASK_START                   109
#define ID_TASK_SHOW_PROGRESS           110
#define ID_TASK_CHANGE                  111
#define IDD_TASK_PROGRESS               112
#define IDI_MAIN_APP_SMALL              113
#define IDI_MAIN_APP                    114
#define IDD_OPTIONS                     117
#define IDD_OPTIONS_SHEET               117
#define ID_OPTIONS_OPTIONS              118
#define IDD_NEW_TASK_SHEET              118
#define IDD_SCHEDULE_SHEET              119
#define IDD_ARCHIVE_SET                 120
#define IDD_ARCHIVE_SHEET               121
#define IDD_LOAD_ARCH_PRESET            122
#define IDC_HELP_ABOUT                  123
#define IDD_ABOUT                       124
#define IDR_ACCELERATOR1                125
#define IDR_ACCELERATORS                125
#define IDI_ICON2                       129
#define IDI_ICON3                       130
#define IDI_ICON4                       131
#define IDI_ICON5                       132
#define IDI_ICON6                       133
#define IDI_ICON7                       134
#define IDI_ICON8                       135
#define IDI_ICON9                       136
#define IDI_ICON10                      137
#define IDI_ICON12                      139
#define IDI_ICON13                      140
#define IDI_ICON14                      141
#define IDI_ICON15                      142
#define IDI_ICON16                      143
#define IDI_ICON17                      144
#define IDI_ICON18                      145
#define IDI_ICON19                      146
#define IDC_TASK_NAME                   1001
#define IDC_SRC_FOLDER                  1002
#define IDC_INCLUDE_MASK                1003
#define IDC_EXCLUDE_MASK                1004
#define IDC_SUBFOLDERS                  1009
#define IDC_PROGRESS                    1011
#define IDC_TASK_FOLDER                 1012
#define IDC_TASK_INCLUDE_MASK           1013
#define IDC_TASK_EXCLUDE_MASK           1014
#define IDC_PROCEED_FILES               1015
#define IDC_INCLUDED_FILES              1016
#define IDC_EXCLUDE_FILES               1017
#define IDC_EXCLUDED_FILES              1017
#define IDC_DEST_FOLDER                 1018
#define IDC_CHOOSE_DEST_FOLDER          1019
#define IDC_CHOOSE_SRC_FOLDER           1020
#define IDC_INFO                        1020
#define IDC_PROCEED_FOLDERS             1024
#define IDC_AUTO_CLOSE                  1025
#define IDC_ERRORS                      1026
#define IDC_SOUND                       1027
#define IDC_CHOOSE_SOUND                1029
#define IDC_STOP_SOUND                  1030
#define IDC_PlAY_SOUND                  1031
#define IDC_USE_SOUND                   1033
#define IDC_SHOW_PROGRESS               1035
#define IDC_DAY                         1037
#define IDC_Time                        1038
#define IDC_TIME                        1038
#define IDC_LAST_RUN                    1040
#define IDC_NEXT_RUN                    1041
#define IDC_GENERATE_NAME               1043
#define IDC_GENERATE_RESULT             1044
#define IDC_BUTTON1                     1045
#define IDC_ADD_PARAM                   1045
#define IDC_TIME_BLOCK_ADD              1045
#define IDC_ADD_TEMPLATE                1046
#define IDC_DEL_TEMPLATE                1047
#define IDC_EDIT1                       1048
#define IDC_LOG                         1048
#define IDC_ARCHIVER_EXE                1048
#define IDC_TASK_CMD                    1048
#define IDC_LOG_SIZE                    1048
#define IDC_TB_HOUR_HOUR                1048
#define IDC_COMMAND_LINE                1049
#define IDC_PARAMS                      1050
#define IDC_DEL_PARAM                   1051
#define IDC_CHOOSE_ARCHIVER             1053
#define IDC_PARAM                       1055
#define IDC_VALUE                       1056
#define IDC_DO_ARCHIVE                  1057
#define IDC_COMPRESS_LEVEL              1058
#define IDC_SFX                         1059
#define IDC_LOAD_PRESET                 1060
#define IDC_PRESETS                     1061
#define IDC_CHECK1                      1062
#define IDC_DEL_FILES                   1062
#define IDC_SCHEDULE_ACTIVE             1062
#define IDC_LOCK                        1063
#define IDC_TIME_BLOCKS_TREE            1064
#define IDC_BUTTON2                     1065
#define IDC_TIME_BLOCK_DEL              1065
#define IDC_TIME_BLOCK_TYPE             1066
#define IDC_MAIN_TB_TYPE                1066
#define IDC_TB_WEEK_DAY_OF_WEEK         1067
#define IDC_TB_WEEK_DAY_OF_WEEK_ST      1068
#define IDC_TB_HOUR_HOUR_ST             1069
#define IDC_TB_PROPS_FROM_ST            1069
#define IDC_EXECUTE_MIN                 1072
#define IDC_TB_PROPS_FROM               1075
#define IDC_TB_PROPS_USE_PERIOD         1076
#define IDC_TB_PROPS_TO                 1077
#define IDC_EXECUTE_DO_REPEAT           1078
#define IDC_EXECUTE_REPEAT_MIN          1079
#define IDC_EXECUTE_MIN_ST              1080
#define IDC_EXECUTE_REPEAT_MIN_UD       1082
#define IDC_NEXT_RUN_ST                 1083
#define IDC_FINISHED_BYTES              1084
#define IDC_TAB1                        1086

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
